a = (input('digite algo'))
print(f"o tipo primitivo desse valor é {type(a)}")
print(f"so tem espaços?{a.isspace()}")
print(f"é alfabetico?{a.isalpha()}")
print(f"é alfanumerico?{a.isalnum()}")
print(f"esta em maiusculas?{a.isupper()}")
print(f"esta em minusculas?{a.islower()}")
print(f"esta captalizada?{a.istitle()}")
